### ISSUE TITLE
Gray routes should allow you to choose what color of cards you want to use

### ISSUE THREAD

**Issue by kadie-weber** [kaden-weber/340TicketToRideClient#18]

**Comment by kadie-weber** [comment]
This might be a pre-req for solving the issue with claiming a gray route requiring locomotives.

**Comment by kadie-weber** [comment]
@zmorty Hey I think there might be some things that need to change with the model here. I am thinking through where we would want to implement the changes for this check. Player.hasTrainCards probably needs to get updated, what logic should the front end take care of?

**Comment by zmorty** [comment]
@kaden-weber So the hasTrainCards will check if they have enough cards of the right type (locomotive or not) and if it is a gray route it will see if they have enough cards of any type (plus locomotives)

**Comment by zmorty** [comment]
@kaden-weber I was thinking though that we should allow the user to select which cards he wants to use to claim a route.

**Comment by kadie-weber** [comment]
okay great! I just wasn't sure if that was what was happening in hasTrainCards. Then I will get going on a UI element for that.
