### ISSUE TITLE
routes can't be claimed reliably

### ISSUE THREAD

**Issue by kadie-weber** [kaden-weber/340TicketToRideClient#9]

**Comment by Decongo** [comment]
I've noticed that you can't claim gray routes unless you have the required number of locomotives, but you should be able to use any color.

Also, when claiming one part of a double route, sometimes the wrong line gets shaded in. It looks like the correct route is actually claimed, the map just makes it look like you claimed the other one.

**Comment by kadie-weber** [comment]
Yes! Great detective work. I'm not sure if the first thing is my issue but I can track it down, as for the second one, I need to change how I made the list of routes, right now there is no way to keep track of whether a route is a second route or not... there needs to be an indicator because the double gray routes are exactly similar. 
@Decongo if you have time you could look into the first issue since I'm not sure where on the stack that logic is happening. I'll let you know if I finish the second fix before tomorrow. 
Also, were you testing that by yourself? If so how can I do the same?

**Comment by Decongo** [comment]
Oh I just go into the Game class and change the minimum player count from 2 to 1 on line 152

**Comment by kadie-weber** [comment]
is that all? I get a null object reference when I confirm my destination card selection...
NVM - I hadn't updated!

**Comment by kadie-weber** [comment]
okay, the double route problem should be fixed, let me know if you find any more issues with it, the gray route issue will be taken care of in the issue with letting the user pick which color to use.
